name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get the latest commit message
      - name: Get the commit message
        id: get_commit_message
        run: echo "commit_message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      # Create a release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: r.${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this release:
            - ${{ env.commit_message }}
          draft: false
          prerelease: false
